# Generated by Django 4.1.4 on 2022-12-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_telemetrydata_last_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
