# Generated by Django 4.1.2 on 2023-01-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exercise_enabled'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercisetag',
            name='unique_course_tag',
        ),
        migrations.RenameField(
            model_name='exercisetag',
            old_name='name',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='exercisetag',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddField(
            model_name='exercisetag',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='exercisetag',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='unique_course_tag'),
        ),
    ]
